### ISSUE TITLE
what is list.txt

### ISSUE THREAD

**Issue by l-guo** [ironiksk/pyannote-db-librispeech#2]
hi
I am trying to use lirispeech database in pyannote
but I got an error as below:

Traceback (most recent call last):
  File "pyannote-db-librispeech/LibriSpeech/generate.py", line 224, in <module>
    init_database('/user/data3/tmp/user1/LibriSpeech', ['dev-clean', 'test-clean','train-clean'], '/user/data3/tmp/user1/pyannote-db-librispeech/LibriSpeech', '/user/data3/tmp/user1/LibriSpeech/wav')
  File "pyannote-db-librispeech/LibriSpeech/generate.py", line 213, in init_database
    duration = get_wav_duration(sample_path + '.wav'),
  File "/homes/user1/.local/lib/python3.5/site-packages/pyannote/audio/features/utils.py", line 46, in get_wav_duration
    y, sample_rate, _ = pysndfile.sndio.read(wav)
  File "/homes/user1/.local/lib/python3.5/site-packages/pysndfile/sndio.py", line 74, in read
    sf  = PySndfile(name)
  File "_pysndfile.pyx", line 613, in _pysndfile.PySndfile.__cinit__ (_pysndfile.cpp:4698)
OSError: PySndfile::error while opening b'/user/data3/tmp/user1/LibriSpeech/wav/1272-135031.wav'
        ->b'System error : No such file or directory

**Comment by l-guo** [comment]
I fixed the problem!
thank you for your source!

**Comment by jan-bk** [comment]
Hi I-guo,

I am encountering the same problem. Could you share how you fixed it? Thanks!

**Comment by l-guo** [comment]
please check every step when creating the list.txt
my problem is the wrong file name
